# Generated by Django 3.2.23 on 2025-01-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_router_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuelstation',
            table='route_fuelstation',
        ),
    ]
